language: c

env:
  - LUA='Lua 5.1'
  - LUA='Lua 5.2'
  - LUA='LuaJIT 2.0'

before_install:
  - bash .travis_setup.sh

install:
  - sudo apt-get update -qq
  - sudo luarocks install luasec
  - sudo apt-get install -qq libev-dev
  - sudo luarocks install lua-ev scm --server=http://luarocks.org/repositories/rocks-scm/
  - sudo luarocks install copas
  - sudo luarocks install moonscript
  - sudo luarocks make

script: busted

branches:
  except:
    - gh-pages

notifications:
  slack: olivinelabs:ZFLBu3JQfLAlTn7eNeh7rott
